[metadata]
name = "d"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat"]

[source]
command = "fd -t f . $HOME/.config"

[preview]
command = "bat --wrap=character --color=always '{}'"

[keybindings]
ctrl-e = "actions:edit"

[actions.edit]
description = "Edit the file"
command = "vim {}"
mode = "execute"
