# ~/.bashrc: executed by bash(1) for non-login shells.
# exports
export EDITOR=vim
export VISUAL=vim
export PAGER=bat
export PATH=$HOME/.local/bin:$PATH
export GOPATH=$HOME/.local/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.local/cargo/bin
export CARGO_HOME=$HOME/.local/cargo

source $HOME/.config/alias

set -o vi

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

unset color_prompt force_color_prompt

# tab completion
[[ $- = *i* ]] && bind TAB:menu-complete

## the prompt.
PS1='\n$PWD\n\$: '

## functions
mcd() {
	mkdir -p $1
	cd $1
}

g() {
	cd $1
	ls -FpX --color=always --group-directories-first
}

rml() {
	trash-put $1
	ls -FpX --color=always --group-directories-first
	## if i wanna make me move to the folder, sigh
	## so for now, i gotta move to the right place first
}

mt() {
	sudo mount /dev/$1 $HOME/usb
	}

umt() {
	sudo umount $HOME/usb
	}

function add-dic {
	sudo tar -xjvf $1 -C /usr/share/stardict/dic
}

